### ISSUE TITLE
.tkmファイルへのコンバータなどは共有可能でしょうか？

### ISSUE THREAD

**Issue by yonezawashin** [shoeisha-books/hlsl-grimoire-sample#3]
MiniEngineでゲーム制作にトライしてみようと思ったのですが、.tkmファイルへどうやってゲーム素材を変換するかが壁となりゲーム制作をできずにいます。
もし.tkmへのコンバータなどあれば共有頂けると幸いです。

**Comment by KawaharaKiyohara** [comment]
まず、次のリポジトリのクローンを行なってください。

https://github.com/KawaharaKiyohara/k2Engine

本書籍のMiniEngineは、このk2Engineからグラフィック周りのプログラムを抽出したものです。
この中にコンバーターがあります。このコンバーターは3dsMaxでしか動作しません。3dsMax2021が最も安定して動作すると思います。3dsMax2022は動作未確認です。
もし、学生さんであれば、3dsMaxはアカデミックライセンスで無料で使えるので試してみてください。

「k2Engine/K2Engineについて.pdf」の次のページを読んでみてください。
モデルを出力するためのドキュメント書かれています。
4ページ目〜6ページ目　コンバーターのセットアップの仕方
9ページ目〜12ページ目　tkmファイルの保存の仕方
14ページ目〜19ページ目　マテリアルの設定の仕方

また、配布しているMiniEngineはアニメーションを行うためのクラスもあるので、アニメーションを流すことも可能です。
(ただし、スキニングを行う頂点シェーダーを書く必要がありますが。)

ついでに、下記のリポジトリはさらにMiniEngineに近い低レベルなエンジンのリポジトリです。こちらであればアニメーションを行うシェーダーもあります。参考にしてみてください。

https://github.com/KawaharaKiyohara/k2EngineLow

**Comment by KawaharaKiyohara** [comment]
もし他に要望などありましたら、再度issueを送ってください。
一旦closeします。
